//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.30 at 12:49:43 PM PST
//


package com.tableausoftware.documentation.api.rest.bindings;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.tableausoftware.documentation.api.rest.bindings package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tableausoftware.documentation.api.rest.bindings
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GranteeCapabilitiesType }
     *
     */
    public GranteeCapabilitiesType createGranteeCapabilitiesType() {
        return new GranteeCapabilitiesType();
    }

    /**
     * Create an instance of {@link SiteType }
     *
     */
    public SiteType createSiteType() {
        return new SiteType();
    }

    /**
     * Create an instance of {@link TsResponse }
     *
     */
    public TsResponse createTsResponse() {
        return new TsResponse();
    }

    /**
     * Create an instance of {@link TableauCredentialsType }
     *
     */
    public TableauCredentialsType createTableauCredentialsType() {
        return new TableauCredentialsType();
    }

    /**
     * Create an instance of {@link GroupType }
     *
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link PermissionsType }
     *
     */
    public PermissionsType createPermissionsType() {
        return new PermissionsType();
    }

    /**
     * Create an instance of {@link ProjectType }
     *
     */
    public ProjectType createProjectType() {
        return new ProjectType();
    }

    /**
     * Create an instance of {@link WorkbookType }
     *
     */
    public WorkbookType createWorkbookType() {
        return new WorkbookType();
    }

    /**
     * Create an instance of {@link TsRequest }
     *
     */
    public TsRequest createTsRequest() {
        return new TsRequest();
    }

    /**
     * Create an instance of {@link CapabilityType }
     *
     */
    public CapabilityType createCapabilityType() {
        return new CapabilityType();
    }

    /**
     * Create an instance of {@link GranteeCapabilitiesType.Capabilities }
     *
     */
    public GranteeCapabilitiesType.Capabilities createGranteeCapabilitiesTypeCapabilities() {
        return new GranteeCapabilitiesType.Capabilities();
    }

}
