//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.30 at 12:49:43 PM PST
//

package com.tableausoftware.documentation.api.rest.bindings;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for paginationType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="paginationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="pageNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="pageSize" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="totalAvailable" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "paginationType")
public class PaginationType {

    @XmlAttribute(name = "pageNumber", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger pageNumber;
    @XmlAttribute(name = "pageSize", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger pageSize;
    @XmlAttribute(name = "totalAvailable", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalAvailable;

    /**
     * Gets the value of the pageNumber property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getPageNumber() {
        return pageNumber;
    }

    /**
     * Sets the value of the pageNumber property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     *
     */
    public void setPageNumber(BigInteger value) {
        this.pageNumber = value;
    }

    /**
     * Gets the value of the pageSize property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     *
     */
    public void setPageSize(BigInteger value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the totalAvailable property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getTotalAvailable() {
        return totalAvailable;
    }

    /**
     * Sets the value of the totalAvailable property.
     *
     * @param value
     *            allowed object is {@link BigInteger }
     *
     */
    public void setTotalAvailable(BigInteger value) {
        this.totalAvailable = value;
    }

}
